#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
  Project Title: 3.1.4
  Team Members: Drew Edwards; Caleb Allington
  Date: 1/28/2020
  Section: Part 4C: Additional Practice


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces
	int LINETHRESH = 1441;
	while(true)  {
		if (SensorValue(bumpSwitch) == 1)  {
			if(SensorValue[lineFollower]>LINETHRESH )
				setServo(servoMotor, 127);
			else
				setServo(servoMotor, -127);
		}
		else
			setServo(servoMotor, 0);
	}
}
