#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: 3.1.5
  Team Members: Drew Edwards, Caleb Allington
  Date: 1/29/2020
  Section: Part 1: Using a Variable to Loop 'n' Lines


  Task Description:


  Pseudocode:
start
	Declarations
		num motorCount
	motorCount = 0
	while motorCount < 3
		rightMotor to 95
		wait 2
		stop rightMotor
		wait 2
		motorCount = motorCount + 1
	endwhile
stop

*/

task main()
{                                     //Program begins, insert code within curly braces
	int MOTORMAX = 127;
	int x = 0;
	for (int x = 0; x < 20; x++)  {
		if (x % 2 == 0)
			startMotor(rightMotor, MOTORMAX);
		else
			startMotor(rightMotor, -MOTORMAX);
		wait(0.5);
	}
}
